### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DerHobbs** [pepski1270/weapon_log#1]
[   script:weapon_log] SCRIPT ERROR: @weapon_log/Server/Server.lua:140: attempt to concatenate a nil value (global '_license2')
[   script:weapon_log] > GetPlayerDetails (@weapon_log/Server/Server.lua:140)
[   script:weapon_log] > handler (@weapon_log/Server/Server.lua:48)

**Comment by pepski1270** [comment]
fixed. redownload server.lua
